steps:
  # Debugging step (optional but highly recommended)
  - name: 'alpine'
    entrypoint: 'sh'
    args: ['-c', 'ls -R /workspace']

  # Main execution step
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -c
      - |
        bq query --use_legacy_sql=false --project_id=${PROJECT_ID} < /workspace/data_pipeline/sql/clean_and_transform_data.sql

  # Add test step
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -c
      - |
        bq query --use_legacy_sql=false --project_id=${PROJECT_ID} < /workspace/data_pipeline/tests/test_cleaned_data.sql
        bq query --use_legacy_sql=false --project_id=${PROJECT_ID} < /workspace/data_pipeline/tests/test_transformed_data.sql
        bq query --use_legacy_sql=false --project_id=${PROJECT_ID} < /workspace/data_pipeline/tests/test_data_completeness.sql
        bq query --use_legacy_sql=false --project_id=${PROJECT_ID} < /workspace/data_pipeline/tests/test_referential_integrity.sql
timeout: 600s

options:
  logging: CLOUD_LOGGING_ONLY