options:
  logging: CLOUD_LOGGING_ONLY
steps:
  # Step 1: Deploy currency-function
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - functions
      - deploy
      - currency-handler
      - --runtime=python310
      - --trigger-topic=currency-topic
      - --entry-point=currency_handler
      - --source=currency-function
      - --project=pub-sub-1233
      - --region=us-central1
      - --timeout=60s
      - --memory=128MB
      - --env-vars-file=.env.yaml

  # Step 2: Deploy rate_updater
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - functions
      - deploy
      - rate-updater
      - --runtime=python310
      - --trigger-topic=bigtable-to-bq
      - --entry-point=get_latest_rate_and_update_bq
      - --source=rate_updater
      - --project=pub-sub-1233
      - --region=us-central1
      - --timeout=60s
      - --memory=256MB
      - --env-vars-file=.env.yaml

timeout: 300s
