steps:
  # Deploy currency-handler function
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - functions
      - deploy
      - currency-handler
      - --runtime=python310
      - --trigger-topic=currency-topic
      - --entry-point=currency_handler
      - --region=us-central1
      - --service-account=pub-sub-1233@appspot.gserviceaccount.com
      - --source=currency-function/
      - --project=pub-sub-1233

  # Deploy get_latest_rate_and_update_bq function
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - functions
      - deploy
      - get_latest_rate_and_update_bq
      - --runtime=python310
      - --trigger-topic=trigger-bigtable-to-bq
      - --entry-point=get_latest_rate_and_update_bq
      - --region=us-central1
      - --set-env-vars=GCP_PROJECT=pub-sub-1233
      - --source=rate_updater/
      - --project=pub-sub-1233

options:
  logging: CLOUD_LOGGING_ONLY
