steps:
  # Deploy Function 1: currency-handler (writes to Bigtable)
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - functions
      - deploy
      - currency-handler
      - --runtime=python310
      - --trigger-topic=currency-topic
      - --entry-point=currency_handler
      - --source=currency-function
      - --region=us-central1
      - --timeout=60s
      - --memory=256MB
      - --set-env-vars=BIGTABLE_INSTANCE=currency-instance,BIGTABLE_TABLE=currency-rates

  # Deploy Function 2: rate-updater (reads from Bigtable, writes to BigQuery)
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - functions
      - deploy
      - rate-updater
      - --runtime=python310
      - --trigger-topic=rate-topic
      - --entry-point=get_latest_rate_and_update_bq
      - --source=rate_updater
      - --region=us-central1
      - --timeout=60s
      - --memory=256MB
      - --set-env-vars=BIGQUERY_DATASET=Staging_Layer,BIGQUERY_TABLE=bq_latest_exchange_rate,BIGTABLE_INSTANCE=currency-instance,BIGTABLE_TABLE=currency-rates

options:
  logging: CLOUD_LOGGING_ONLY
timeout: 300s
