steps:
  # --- Deploy currency-handler Function ---
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      [
        'functions', 'deploy', 'currency-handler',
        '--runtime', 'python310',
        '--trigger-topic', 'currency-topic',
        '--entry-point', 'currency_handler',
        '--region', 'us-central1',
        '--service-account', 'pub-sub-1233@appspot.gserviceaccount.com',
        '--source', 'currency-function/'
      ]

  # --- Deploy get_latest_rate_and_update_bq Function ---
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      [
        'functions', 'deploy', 'get_latest_rate_and_update_bq',
        '--runtime', 'python310',
        '--trigger-topic', 'trigger-bigtable-to-bq',
        '--entry-point', 'get_latest_rate_and_update_bq',
        '--region', 'us-central1',
        '--set-env-vars', 'GCP_PROJECT=pub-sub-1233',
        '--source', 'rate_updater/'
      ]

  # --- (Optional) Trigger currency Cloud Scheduler job manually after deployment ---
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: ['scheduler', 'jobs', 'run', 'currency-scheduler-job', '--location=us-central1']

  # --- (Optional) Trigger rate Cloud Scheduler job manually after deployment ---
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: ['scheduler', 'jobs', 'run', 'trigger-rate-job', '--location=us-central1']

options:
  logging: CLOUD_LOGGING_ONLY
