steps:
  # --- Set up Python environment for testing ---
  - name: 'python:3.10'
    id: 'Run tests for currency-handler'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd currency-function
        pip install --no-cache-dir google-cloud-bigtable google-cloud-core
        echo "Running currency-handler tests..."
        python tests/test_currency_handler.py

  - name: 'python:3.10'
    id: 'Run tests for get_latest_rate_and_update_bq'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd rate_updater
        pip install --no-cache-dir google-cloud-bigtable google-cloud-bigquery google-cloud-core
        echo "Running get_latest_rate_and_update_bq tests..."
        python tests/test_get_latest_rate_and_update_bq.py

  # --- Deploy currency-handler Function ---
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy currency-handler'
    entrypoint: 'gcloud'
    args:
      [
        'functions', 'deploy', 'currency-handler',
        '--runtime', 'python310',
        '--trigger-topic', 'currency-topic',
        '--entry-point', 'currency_handler',
        '--region', 'us-central1',
        '--service-account', 'pub-sub-1233@appspot.gserviceaccount.com',
        '--source', 'currency-function/'
      ]

  # --- Deploy get_latest_rate_and_update_bq Function ---
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy get_latest_rate_and_update_bq'
    entrypoint: 'gcloud'
    args:
      [
        'functions', 'deploy', 'get_latest_rate_and_update_bq',
        '--runtime', 'python310',
        '--trigger-topic', 'trigger-bigtable-to-bq',
        '--entry-point', 'get_latest_rate_and_update_bq',
        '--region', 'us-central1',
        '--set-env-vars', 'GCP_PROJECT=pub-sub-1233',
        '--source', 'rate_updater/'
      ]

  # --- (Optional) Trigger currency Cloud Scheduler job manually after deployment ---
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Trigger currency-scheduler-job'
    entrypoint: 'gcloud'
    args: ['scheduler', 'jobs', 'run', 'currency-scheduler-job', '--location=us-central1']

  # --- (Optional) Trigger rate Cloud Scheduler job manually after deployment ---
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Trigger rate-scheduler-job'
    entrypoint: 'gcloud'
    args: ['scheduler', 'jobs', 'run', 'trigger-rate-job', '--location=us-central1']

options:
  logging: CLOUD_LOGGING_ONLY

timeout: 900s
