steps:
  # --- Test Stage ---
  - name: 'python:3.9'
    entrypoint: 'python'
    args: ['-m', 'unittest', 'discover', '-s', 'currency-function', '-p', 'test_*.py']

  - name: 'python:3.9'
    entrypoint: 'python'
    args: ['-m', 'unittest', 'discover', '-s', 'rate_updater', '-p', 'test_*.py']

  # --- Deploy Currency Function ---
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'functions'
      - 'deploy'
      - 'currency-handler'
      - '--runtime=python310'
      - '--trigger-topic=currency-topic'
      - '--entry-point=currency_handler'
      - '--region=us-central1'
      - '--service-account=pub-sub-1233@appspot.gserviceaccount.com'
      - '--source=currency-function/'
      - '--project=pub-sub-1233'
    waitFor: ['-']

  # --- Deploy Rate Updater Function ---
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'functions'
      - 'deploy'
      - 'rate-updater'
      - '--runtime=python311'
      - '--trigger-topic=trigger-bigtable-to-bq'
      - '--entry-point=get_latest_rate_and_update_bq'
      - '--region=asia-south1'
      - '--source=rate_updater/'
      - '--set-env-vars=GCP_PROJECT=pub-sub-1233,BIGTABLE_INSTANCE_ID=currency-instance,BIGTABLE_TABLE_ID=currency-table'
      - '--timeout=60s'
      - '--memory=256MB'
      - '--service-account=pub-sub-1233@appspot.gserviceaccount.com'
      - '--project=pub-sub-1233'
    waitFor: ['-']

options:
  logging: CLOUD_LOGGING_ONLY
